import { useState } from "react"

const Credits = () => {
  const [showCredits, setShowCredits] = useState(false)
  return (
    <div id="credits">
      <div style={{ float: "right" }}>
        &copy; 2025 Jen "Jowday" Guerra and Steven "Razlo" Bailey
      </div>
      <h3 onClick={() => setShowCredits(!showCredits)}>Credits</h3>
      <ul
        id="credits"
        style={{ display: showCredits ? "block" : "none" }}
      >
        <li>
          <strong>Game Design, Graphics: </strong>Steven "Razlo" Bailey
        </li>
        <li>
          <strong>Code: </strong>Jen "Jowday" Guerra
        </li>
        <li>
          <strong>Rendering Engine: </strong>
          <a
            href="https://react.pixijs.io/"
            target="_blank"
          >
            PixiJS React
          </a>
        </li>
        <li>
          <strong>Color Theme: </strong>
          <a
            href="https://lospec.com/palette-list/lava-gb"
            target="_blank"
          >
            LAVA-GB PALLETE by Aero
          </a>
        </li>
        <li>
          <strong>Sound Hook: </strong>
          <a
            href="https://www.npmjs.com/package/use-sound"
            target="_blank"
          >
            useSound
          </a>{" "}
          by joshwcomeau
        </li>
        <li>
          <strong>SFX generated by: </strong>
          <a
            href="https://sfbgames.itch.io/chiptone"
            target="_blank"
          >
            ChipTone
          </a>{" "}
          and{" "}
          <a
            href="https://sfxr.me/"
            target="_blank"
          >
            jsfxr
          </a>
        </li>
      </ul>
    </div>
  )
}

export default Credits
